// Type declarations for the bundled notifee module.
// The actual bundle is generated by tsdown from notifee-bundle.ts.
// Requires `tsdown` to have been run first to generate dist/notifee.d.ts.
export * from './dist/notifee';
export { default } from './dist/notifee';
